import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="fixed bg-white py-1 px-2">
          This is my new website and currently working on it
        </div>
        {children}
        <div className="space stars1"></div>
        <div className="space stars2"></div>
        <div className="space stars3"></div>
      </body>
    </html>
  );
}
